module.exports = {
  "__version": "4.5.0",
  "Actions": {
    "Renders the dom with a message": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message\">Please correct invalid emails</h2>\n        <div class=\"error-container\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\"></div>\n            ​\n            <div class=\"input\">add more people...</div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    }
  },
  "Layout": {
    "Renders the dom with a message": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message\">Please correct invalid emails</h2>\n        <div class=\"error-container\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\"></div>\n            ​\n            <div class=\"input\">add more people...</div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    },
    "Renders the dom with a empty input": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message\">Please correct invalid emails</h2>\n        <div class=\"error-container\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\"></div>\n            ​\n            <div class=\"input\">add more people...</div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    },
    "Renders the dom with some valid emails": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message\">Please correct invalid emails</h2>\n        <div class=\"error-container\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\">\n              <div class=\"pill\">\n                <span class=\"pill-label\">sameexample@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n            </div>\n            ​\n            <div class=\"input input-active\"\n              contenteditable=\"true\"></div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    },
    "Renders the dom with lots of valid emails": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message\">Please correct invalid emails</h2>\n        <div class=\"error-container\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\">\n              <div class=\"pill\">\n                <span class=\"pill-label\">superfake@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">sameexample@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">superfake@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">sameexample@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n            </div>\n            ​\n            <div class=\"input input-active\"\n              contenteditable=\"true\"></div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    },
    "Renders the dom with some invalid emails": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message error-message-active\">Please correct invalid\n          emails</h2>\n        <div class=\"error-container error-container-active\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\">\n              <div class=\"pill pill-invalid\">\n                <span class=\"pill-label\">invalid</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">example@examplemail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill pill-invalid\">\n                <span class=\"pill-label\">asdfasdfx</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">sameexample@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill pill-invalid\">\n                <span class=\"pill-label\">invalid</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">superfake@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"remove.png\">\n              </div>\n            </div>\n            ​\n            <div class=\"input input-active\"\n              contenteditable=\"true\"></div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    },
    "with a empty input": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message\">Please correct invalid emails</h2>\n        <div class=\"error-container\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\"></div>\n            ​\n            <div class=\"input\">add more people...</div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    },
    "with some valid emails": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message\">Please correct invalid emails</h2>\n        <div class=\"error-container\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\">\n              <div class=\"pill\">\n                <span class=\"pill-label\">sameexample@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n            </div>\n            ​\n            <div class=\"input input-active\"\n              contenteditable=\"true\"></div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    },
    "with lots of valid emails": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message\">Please correct invalid emails</h2>\n        <div class=\"error-container\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\">\n              <div class=\"pill\">\n                <span class=\"pill-label\">superfake@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">sameexample@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">superfake@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">sameexample@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n            </div>\n            ​\n            <div class=\"input input-active\"\n              contenteditable=\"true\"></div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    },
    "with some invalid emails": {
      "1": "<body>\n  <div class=\"emails-input--wrapper\">\n    <div class=\"emails-input\">\n      <div class=\"content\">\n        <h1>Share <b>Board name</b> with others</h1>\n        <h2 class=\"error-message error-message-active\">Please correct invalid\n          emails</h2>\n        <div class=\"error-container error-container-active\">\n          <div class=\"textarea\">\n            <div class=\"pills-group\">\n              <div class=\"pill pill-invalid\">\n                <span class=\"pill-label\">invalid</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">example@examplemail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill pill-invalid\">\n                <span class=\"pill-label\">asdfasdfx</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">sameexample@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill pill-invalid\">\n                <span class=\"pill-label\">invalid</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">superfake@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n              <div class=\"pill\">\n                <span class=\"pill-label\">notreal@gmail.com</span>\n                <img class=\"pill-remove\"\n                  src=\"e88a194ea10f9ebc37fe91d5bbb6d494.png\">\n              </div>\n            </div>\n            ​\n            <div class=\"input input-active\"\n              contenteditable=\"true\"></div>\n          </div>\n        </div>\n      </div>\n      <div class=\"actions\"><button>Add email</button><button>Get emails\n          count</button></div>\n    </div>\n  </div>\n  <!-- <div class=\"emails-input--wrapper\"></div> -->\n  <script src=\"main.js\"></script>\n\n</body>"
    }
  }
}
